require 'digest/sha1'

class User < ActiveRecord::Base
  # ---------------------------------------
  # The following code has been generated by role_requirement.
  # You may wish to modify it to suit your need
  has_and_belongs_to_many :roles

  attr_accessor :admin_role

  has_one :participant, :dependent => :nullify
  validates_presence_of :participant, :message => "must be picked from the drop-down.  Please choose one from the list, or create a new one."
#  delegate :fullname, :to => :participant  # Why isn't delegate working????
  accepts_nested_attributes_for :participant

  # has_role? simply needs to return true or false whether a user has a role or not.
  # It may be a good idea to have "admin" roles return true always
  def has_role?(role_in_question)
    @_list ||= self.roles.collect(&:name)
    return true if @_list.include?("admin")
    (@_list.include?(role_in_question.to_s) )
  end
  # ---------------------------------------

  include Authentication
  include Authentication::ByPassword
  include Authentication::ByCookieToken

  validates_presence_of     :login
  validates_length_of       :login,    :within => 3..40
  validates_uniqueness_of   :login
  validates_format_of       :login,    :with => Authentication.login_regex, :message => Authentication.bad_login_message

  validates_format_of       :name,     :with => Authentication.name_regex,  :message => Authentication.bad_name_message, :allow_nil => true
  validates_length_of       :name,     :maximum => 100

  validates_presence_of     :security_question
  validates_presence_of     :security_answer


  # HACK HACK HACK -- how to do attr_accessible from here?
  # prevents a user from submitting a crafted form that bypasses activation
  # anything else you want your user to change should be added here.
  attr_accessible(:login, :name, :password,
                  :password_confirmation, :security_question,
                  :security_answer, :participant_attributes,
                  :position)

  # Authenticates a user by their login name and unencrypted password.  Returns the user or nil.
  #
  # uff.  this is really an authorization, not authentication routine.
  # We really need a Dispatch Chain here or something.
  # This will also let us return a human error message.
  #
  def self.authenticate(login, password)
    return nil if login.blank? || password.blank?
    u = find_by_login(login.downcase) # need to get the salt
    u && u.authenticated?(password) ? u : nil
  end

  def login=(value)
    write_attribute :login, (value ? value.downcase : nil)
  end

  def email
    participant.try(:email)
  end

  def email=(value)
    if participant
      participant.email = value ? value.downcase : nil
    end
  end

  def administrator?
    login == "administrator" or login == "admin"
  end

  def authorized_for_listing?(param_id)
    id == param_id.to_i
  end

  def quit_staff_and_remain_participant
    self.participant.update_attributes(:user_id => nil)
    self.destroy
  end

  # define readable methods for role access
  Role.all.each do |role|
    define_method "is_#{role.name}?" do
      has_role?(role.name)
    end
  end



  protected



end
